### ISSUE TITLE
Pro Controller usage

### ISSUE THREAD

**Issue by AlreadyNestedHumanWine** [chrislo27/PolyrhythmMania#52]
Is there a way to use a controller instead of a keyboard?

**Comment by chrislo27** [comment]
Hi, unfortunately controllers aren't supported natively. This is because the game was designed for mouse-keyboard inputs only, mainly for the Editor. Controller support is not planned due to its complexity.

You might have some luck running a program like AntiMicroX (https://github.com/AntiMicroX/antimicrox/) which lets you map controller inputs to the keyboard inputs.

**Comment by AlreadyNestedHumanWine** [comment]
nvm I figured it out, I just had to use steam big screen and map inputs
